url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Brandist" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-seo-tag
email: contact@brandist.app
organization_name: brandist.app
